import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from sklearn.datasets import make_swiss_roll

# ==========================================
# 1. 准备数据：生成 2D 瑞士卷
# ==========================================
def get_swiss_roll(n_samples=10000):
    # sklearn 自带的瑞士卷是 3D 的，我们只取 x 和 z 轴变成 2D
    data, _ = make_swiss_roll(n_samples, noise=0.5)
    data = data[:, [0, 2]] / 10.0  # 缩放到大致 [-1.5, 1.5] 的范围，这步归一化对神经网络非常重要！
    return torch.tensor(data, dtype=torch.float32)

dataset = get_swiss_roll()
print("Dataset shape:", dataset.shape)

# ==========================================
# 2. 定义极简的网络：处理 (x, t) 的 5-layer MLP
# ==========================================
class VectorFieldMLP(nn.Module):
    def __init__(self, hidden_dim=256):
        super().__init__()
        # 输入是 2D 的坐标 x，加上 1D 的时间 t，所以输入维度是 3
        self.net = nn.Sequential(
            nn.Linear(3, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 2)  # 输出必须是 2D 的速度场 v (因为数据是 2D 的)
        )

    def forward(self, x, t):
        # 很多新手死在这一步：怎么把标量 t 喂给网络？
        # 最简单粗暴（且在 2D 任务中绝对有效）的方法：直接拼在一起！
        # t 的 shape 是 [batch_size, 1]，x 是 [batch_size, 2]
        inputs = torch.cat([x, t], dim=-1) # shape 变成 [batch_size, 3]
        return self.net(inputs)

model = VectorFieldMLP().cuda() if torch.cuda.is_available() else VectorFieldMLP()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# ==========================================
# 3. 训练过程 (Rectified Flow / Flow Matching)
# ==========================================
# 目标：让模型学习预测从噪声(p0)指向数据(p1)的速度向量 v = x1 - x0
batch_size = 512
epochs = 2000

print("开始训练...")
model.train()
for epoch in range(epochs):
    # 1. 随机抽写真实数据 x1 (代表目标分布 p1)
    idx = torch.randint(0, len(dataset), (batch_size,))
    x1 = dataset[idx].to(next(model.parameters()).device)
    
    # 2. 随机抽取标准高斯噪声 x0 (代表起始分布 p0)
    x0 = torch.randn_like(x1)
    
    # 3. 随机抽取时间步 t ~ Uniform(0, 1)
    t = torch.rand((batch_size, 1), device=x1.device)
    
    # 4. 构造中间状态 xt (这是 Rectified Flow 的直线路径公式)
    xt = t * x1 + (1 - t) * x0
    
    # 5. 目标速度场 v_target 就是指向目标的直线向量
    v_target = x1 - x0
    
    # 6. 让模型预测当前状态 xt 下的速度
    v_pred = model(xt, t)
    
    # 7. 计算 MSE 损失并更新
    loss = torch.nn.functional.mse_loss(v_pred, v_target)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 500 == 0:
        print(f"Epoch {epoch:04d} | Loss: {loss.item():.4f}")

# ==========================================
# 4. 推理过程 (使用欧拉法解 ODE 生成数据)
# ==========================================
print("训练完成，开始生成图像...")
model.eval()

# 我们想要生成 2000 个点来看看形状
n_generate = 2000
with torch.no_grad():
    # 1. 从纯高斯噪声开始 (t = 0)
    x_gen = torch.randn((n_generate, 2)).to(next(model.parameters()).device)
    
    # 2. 定义时间步数 (积分步数)
    n_steps = 100
    dt = 1.0 / n_steps
    
    # 3. 欧拉法 (Euler Method) 一步步往前走
    for i in range(n_steps):
        # 当前的时间标量
        t_val = i / n_steps
        # 扩充成张量 [n_generate, 1]
        t_tensor = torch.full((n_generate, 1), t_val, device=x_gen.device)
        
        # 让模型预测速度
        v = model(x_gen, t_tensor)
        
        # 按照速度方向走一小步： x_{t+dt} = x_t + v * dt
        x_gen = x_gen + v * dt

# ==========================================
# 5. 可视化结果
# ==========================================
x_gen_np = x_gen.cpu().numpy()
data_np = dataset[:n_generate].numpy()

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.title("Ground Truth (Swiss Roll)")
plt.scatter(data_np[:, 0], data_np[:, 1], s=2, c='blue', alpha=0.5)
plt.xlim(-2, 2); plt.ylim(-2, 2)

plt.subplot(1, 2, 2)
plt.title("Generated by Rectified Flow")
plt.scatter(x_gen_np[:, 0], x_gen_np[:, 1], s=2, c='red', alpha=0.5)
plt.xlim(-2, 2); plt.ylim(-2, 2)

plt.show()